# Generated by Django 3.0.6 on 2020-05-24 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователи'},
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mark', models.CharField(max_length=3, verbose_name='Оценка')),
                ('reporting_form', models.CharField(choices=[('exam', 'Экзамен'), ('offset', 'Зачет')], max_length=20, verbose_name='Форма отчетности')),
                ('date', models.DateField(null=True, verbose_name='Дата')),
                ('FIO', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CMSWeb.Users', verbose_name='ФИО студента')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CMSWeb.Groups', verbose_name='Группа')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='CMSWeb.Subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Успеваемость',
            },
        ),
    ]
