# Generated by Django 3.0.6 on 2020-05-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance',
            name='reporting_form',
            field=models.CharField(choices=[('Экзамен', 'Экзамен'), ('Зачет', 'Зачет')], max_length=20, verbose_name='Форма отчетности'),
        ),
    ]
