# Generated by Django 3.0.6 on 2020-05-26 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWeb', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='CMSWeb.Groups', verbose_name='Группа'),
        ),
    ]
