# Generated by Django 3.0.6 on 2020-05-26 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWeb', '0002_auto_20200526_1812'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Учебные группы', 'verbose_name_plural': 'Учебные группы'},
        ),
    ]
