# Generated by Django 3.0.6 on 2020-05-24 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWeb', '0002_auto_20200524_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='groups',
            options={'verbose_name': 'Группы', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='performance',
            options={'verbose_name': 'Успеваемость', 'verbose_name_plural': 'Успеваемость'},
        ),
        migrations.AlterModelOptions(
            name='subject',
            options={'verbose_name': 'Предметы', 'verbose_name_plural': 'Предметы'},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'verbose_name': 'Пользователи', 'verbose_name_plural': 'Пользователи'},
        ),
    ]
