# Generated by Django 3.0.6 on 2020-05-26 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CMSWeb', '0003_auto_20200524_2058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groups',
            name='course',
            field=models.CharField(default='-', max_length=2, verbose_name='Курс'),
        ),
        migrations.AlterField(
            model_name='groups',
            name='group',
            field=models.CharField(default='-', max_length=200, verbose_name='Группа'),
        ),
    ]
